title: Kuchnia Senatora
url: "https://kuchnia.senator.lu"
baseurl: ""
markdown: kramdown
theme: minima
permalink: /:categories/:title/
collections:
  recipes:
    output: true
    permalink: /recipes/:name/
